[package]
name = "proj"
version = "1.2.1-alpha.0"
authors = ["Alex LaFroscia <alex@lafroscia.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_fs = "1.0.0"
clap = "2.33.3"
